---

- name: Fail if required playbook-state-preserver settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - playbook_state_preserve_uid
    - playbook_state_preserve_gid

- when: playbook_state_preserve_vars | bool
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/preserve_vars.yml"

- when: playbook_state_commit_hash | bool
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/preserve_commit_hash.yml"
