---

- name: Fail if required playbook-state-preserver vars.yml-preservation settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using vars.yml-preservation.
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - playbook_state_var_dst

- name: Preserve vars.yml on the server for easily restoring if it gets lost later on
  ansible.builtin.copy:
    src: "{{ playbook_state_var_src }}"
    dest: "{{ playbook_state_var_dst }}"
    owner: "{{ playbook_state_preserve_uid }}"
    group: "{{ playbook_state_preserve_gid }}"
    mode: "{{ playbook_state_preserve_mode }}"
